name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Reconfigure git to use HTTP authentication
      run: >
        GIT_TRACE=1 git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
